#!/usr/bin/with-contenv bash

log() {
    local message="$1"
    local timestamp=$(date +"%Y.%m.%dT%H:%M:%S")
    echo "${timestamp} (qbt-portchecker) ${message}"
}

log "init"https://github.com/TechClusterHQ/qbt-portchecker wie findest du die README?